# Generated by Django 4.2.7 on 2023-11-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('right_answer', models.CharField(max_length=256)),
                ('wrong_answer_1', models.CharField(max_length=256)),
                ('wrong_answer_2', models.CharField(max_length=256)),
                ('wrong_answer_3', models.CharField(max_length=256)),
                ('wrong_answer_4', models.CharField(max_length=256)),
            ],
        ),
    ]
