# Generated by Django 4.2.7 on 2023-11-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Character', '0004_remove_question_likes_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
